Tested and verified, added variables for kube versions

diff --git a/terraform/data/aws_launch_configuration_nodes_user_data b/terraform/data/aws_launch_configuration_nodes_user_data
--- a/terraform/data/aws_launch_configuration_nodes_user_data
+++ b/terraform/data/aws_launch_configuration_nodes_user_data
@@ -17,13 +17,13 @@ set -o errexit
 set -o nounset
 set -o pipefail
 
-NODEUP_URL=https://kubeupv2.s3.amazonaws.com/kops/1.3/linux/amd64/nodeup
+NODEUP_URL=${NODEUP_URL}
 NODEUP_HASH=
 
 function ensure-install-dir() {
   INSTALL_DIR="/var/cache/kubernetes-install"
-  mkdir -p \$${INSTALL_DIR}
-  cd \$${INSTALL_DIR}
+  mkdir -p $${INSTALL_DIR}
+  cd $${INSTALL_DIR}
 }
 
 # Retry a download until we get it. Takes a hash and a set of URLs.
@@ -36,18 +36,18 @@ download-or-bust() {
 
   urls=( $* )
   while true; do
-    for url in "\$${urls[@]}"; do
-      local file="\$${url##*/}"
-      rm -f "\$${file}"
-      if ! curl -f --ipv4 -Lo "\$${file}" --connect-timeout 20 --retry 6 --retry-delay 10 "\$${url}"; then
-        echo "== Failed to download \$${url}. Retrying. =="
-      elif [[ -n "\$${hash}" ]] && ! validate-hash "\$${file}" "\$${hash}"; then
-        echo "== Hash validation of \$${url} failed. Retrying. =="
+    for url in "$${urls[@]}"; do
+      local file="$${url##*/}"
+      rm -f "$${file}"
+      if ! curl -f --ipv4 -Lo "$${file}" --connect-timeout 20 --retry 6 --retry-delay 10 "$${url}"; then
+        echo "== Failed to download $${url}. Retrying. =="
+      elif [[ -n "$${hash}" ]] && ! validate-hash "$${file}" "$${hash}"; then
+        echo "== Hash validation of $${url} failed. Retrying. =="
       else
-        if [[ -n "\$${hash}" ]]; then
-          echo "== Downloaded \$${url} (SHA1 = \$${hash}) =="
+        if [[ -n "$${hash}" ]]; then
+          echo "== Downloaded $${url} (SHA1 = $${hash}) =="
         else
-          echo "== Downloaded \$${url} =="
+          echo "== Downloaded $${url} =="
         fi
         return
       fi
@@ -63,9 +63,9 @@ validate-hash() {
   local -r expected="$2"
   local actual
 
-  actual=$(sha1sum \$${file} | awk '{ print $1 }') || true
-  if [[ "\$${actual}" != "\$${expected}" ]]; then
-    echo "== \$${file} corrupted, sha1 \$${actual} doesn't match expected \$${expected} =="
+  actual=$(sha1sum $${file} | awk '{ print $1 }') || true
+  if [[ "$${actual}" != "$${expected}" ]]; then
+    echo "== $${file} corrupted, sha1 $${actual} doesn't match expected $${expected} =="
     return 1
   fi
 }
@@ -78,19 +78,19 @@ function try-download-release() {
   # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
   # optimization.
 
-  local -r nodeup_urls=( $(split-commas "\$${NODEUP_URL}") )
-  local -r nodeup_filename="\$${nodeup_urls[0]##*/}"
-  if [[ -n "\$${NODEUP_HASH:-}" ]]; then
-    local -r nodeup_hash="\$${NODEUP_HASH}"
+  local -r nodeup_urls=( $(split-commas "$${NODEUP_URL}") )
+  local -r nodeup_filename="$${nodeup_urls[0]##*/}"
+  if [[ -n "$${NODEUP_HASH:-}" ]]; then
+    local -r nodeup_hash="$${NODEUP_HASH}"
   else
   # TODO: Remove?
     echo "Downloading sha1 (not found in env)"
-    download-or-bust "" "\$${nodeup_urls[@]/%/.sha1}"
-    local -r nodeup_hash=$(cat "\$${nodeup_filename}.sha1")
+    download-or-bust "" "$${nodeup_urls[@]/%/.sha1}"
+    local -r nodeup_hash=$(cat "$${nodeup_filename}.sha1")
   fi
 
-  echo "Downloading nodeup (\$${nodeup_urls[@]})"
-  download-or-bust "\$${nodeup_hash}" "\$${nodeup_urls[@]}"
+  echo "Downloading nodeup ($${nodeup_urls[@]})"
+  download-or-bust "$${nodeup_hash}" "$${nodeup_urls[@]}"
 
   chmod +x nodeup
 }
@@ -109,7 +109,7 @@ function download-release() {
 
 function run-nodeup() {
   sleep 1
-  ( cd \$${INSTALL_DIR}; ./nodeup --conf=/var/cache/kubernetes-install/kube_env.yaml --v=8 )
+  ( cd $${INSTALL_DIR}; ./nodeup --conf=/var/cache/kubernetes-install/kube_env.yaml --v=8 )
 }
 
 ####################################################################################
@@ -120,10 +120,7 @@ echo "== nodeup node config starting =="
 ensure-install-dir
 
 cat > kube_env.yaml << __EOF_KUBE_ENV
-Assets:
-- b0418c796db823051ba7b1acb2ac414052e64f89@https://storage.googleapis.com/kubernetes-release/release/v1.4.0/bin/linux/amd64/kubelet
-- 0b0aef7df796a897c84f17fcc77ad7eb9b68220d@https://storage.googleapis.com/kubernetes-release/release/v1.4.0/bin/linux/amd64/kubectl
-- 86966c78cc9265ee23f7892c5cad0ec7590cec93@https://storage.googleapis.com/kubernetes-release/network-plugins/cni-8a936732094c0941e1543ef5d292a1f4fffa1ac5.tar.gz
+${KUBE_ASSETS}
 ClusterName: ${FQDN}
 ConfigBase: s3://${KOPS}/${FQDN}
 InstanceGroupName: nodes
